rplidar_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    serial_baudrate: 115200
    frame_id: "laser"
    inverted: false
    angle_compensate: true
    scan_mode: "Standard"
    auto_standby: false
    max_distance: 8.0
    scan_frequency: 5.0
