slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    enable_interactive_mode: true
    publish_map: true
    map_start_at_dock: false  # Bắt đầu tạo bản đồ mới
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"
    transform_publish_period: 0.02
    map_start_pose: [0.0, 0.0, 0.0]  # Thêm tọa độ ban đầu
    transform_tolerance: 0.2  # Thêm để hỗ trợ thiếu odometry
    resolution: 0.05
    message_filter_queue_size: 50
    max_laser_range: 12.0
    minimum_travel_distance: 0.5
    minimum_time_interval: 0.5
    minimum_travel_heading: 0.5
    map_update_interval: 0.5  # Giảm để cập nhật nhanh hơn
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
